export const KNOWLEDGE_GRAPH = {
  Nodes: [
    {
      id: 1,
      label: 'David Ceballos',
      type: 'Personal',
      level: 1,
    },
    {
      id: 2,
      label: 'Sr. Frontend Engineer',
      type: 'Professional',
      level: 1,
    },
    {
      id: 3,
      label: 'UI/UX and Design Enthusiast',
      type: 'Personal',
      level: 1,
    },
    {
      id: 4,
      label: 'Tech Stack Projects',
      type: 'Professional',
      level: 2,
      details: '3D Model Inspector at Nifty Island',
    },
    {
      id: 14,
      label: 'Arcane Tongues Design Work',
      type: 'Personal',
      level: 3,
      image: 'Example of Design Work',
    },
    {
      id: 15,
      label: 'Soccer 7v7 League Champion',
      type: 'Personal',
      level: 3,
    },
    {
      id: 16,
      label: 'Skateboarding Inspiration',
      type: 'Personal',
      level: 3,
    },
    {
      id: 17,
      label: "Interest in Kids' Learning Software",
      type: 'Personal',
      level: 3,
    },
    {
      id: 18,
      label: 'Investment in $BEAM',
      type: 'Personal',
      level: 3,
    },
    {
      id: 19,
      label: 'Reading: Dieter Rams - The Complete Works',
      type: 'Personal',
      level: 3,
    },
    {
      id: 20,
      label: 'French Press Coffee',
      type: 'Personal',
      level: 3,
    },
    {
      id: 21,
      label: 'Active in Design and Fashion Twitter',
      type: 'Personal',
      level: 3,
    },
    {
      id: 22,
      label: 'Favorite Bands (Spotify API)',
      type: 'Personal',
      level: 3,
    },
    {
      id: 23,
      label: 'Songwriting and Music Production',
      type: 'Personal',
      level: 3,
    },
    {
      id: 24,
      label: 'Alt Rock/Post Hardcore Band - Hungry Hearts',
      type: 'Personal',
      level: 3,
      link: "Band's Music Link",
    },
    {
      id: 25,
      label: '3D Model Inspector Challenges',
      type: 'Professional',
      level: 4,
      details:
        'Handling multiple file types and maintaining state for multi asset uploads.',
    },
    {
      id: 26,
      label: '3D Model Inspector Features',
      type: 'Professional',
      level: 4,
      details: 'Customizable environment, lighting, background.',
    },
    {
      id: 27,
      label: 'Generative AI Learning App Concept',
      type: 'Personal',
      level: 4,
    },
    {
      id: 28,
      label: 'Twitter Sources for CRISPR Information',
      type: 'Personal',
      level: 4,
      details:
        'Following accounts like @0xca0a, @jaysonJoyride, @hunimona, @laurentdelRey.',
    },
    {
      id: 29,
      label: 'Music Production Tools',
      type: 'Personal',
      level: 4,
      details: 'FL Studio, Fender Jazz Bass, Songwriting.',
    },
    {
      id: 30,
      label: 'Hungry Hearts Album: Born In Flames',
      type: 'Personal',
      level: 4,
      details: 'Highlight Songs: Lighthouse, Supernatural.',
    },
    {
      id: 31,
      label: 'Coffee Preparation: Cinnamon Addition',
      type: 'Personal',
      level: 4,
    },
    {
      id: 32,
      label: 'Spotify Favorite Genres',
      type: 'Personal',
      level: 4,
      details: 'Posthardcore, Trap, Spanish.',
    },
  ],
  Edges: [
    {
      from: 1,
      to: 2,
      relationship: 'Profession',
      direction: 'bidirectional',
    },
    {
      from: 1,
      to: 3,
      relationship: 'Interest',
      direction: 'bidirectional',
    },
    {
      from: 2,
      to: 4,
      relationship: 'Uses',
      direction: 'unidirectional',
    },
    {
      from: 4,
      to: 14,
      relationship: 'Design Project',
      direction: 'unidirectional',
    },
    {
      from: 1,
      to: 15,
      relationship: 'Achievement',
      direction: 'unidirectional',
    },
    {
      from: 1,
      to: 16,
      relationship: 'Inspired By',
      direction: 'unidirectional',
    },
    {
      from: 1,
      to: 17,
      relationship: 'Interest',
      direction: 'unidirectional',
    },
    {
      from: 1,
      to: 18,
      relationship: 'Invested In',
      direction: 'unidirectional',
    },
    {
      from: 1,
      to: 19,
      relationship: 'Reading',
      direction: 'unidirectional',
    },
    {
      from: 1,
      to: 20,
      relationship: 'Preference',
      direction: 'unidirectional',
    },
    {
      from: 1,
      to: 21,
      relationship: 'Interest',
      direction: 'unidirectional',
    },
    {
      from: 1,
      to: 22,
      relationship: 'Music Taste',
      direction: 'unidirectional',
    },
    {
      from: 1,
      to: 23,
      relationship: 'Skill',
      direction: 'unidirectional',
    },
    {
      from: 23,
      to: 24,
      relationship: 'Experience',
      direction: 'unidirectional',
    },
    {
      from: 4,
      to: 25,
      relationship: 'Challenge',
      direction: 'unidirectional',
    },
    {
      from: 4,
      to: 26,
      relationship: 'Feature',
      direction: 'unidirectional',
    },
    {
      from: 17,
      to: 27,
      relationship: 'Concept',
      direction: 'unidirectional',
    },
    {
      from: 18,
      to: 28,
      relationship: 'Information Source',
      direction: 'unidirectional',
    },
    {
      from: 23,
      to: 29,
      relationship: 'Tools',
      direction: 'unidirectional',
    },
    {
      from: 24,
      to: 30,
      relationship: 'Music Work',
      direction: 'unidirectional',
    },
    {
      from: 20,
      to: 31,
      relationship: 'Preparation Method',
      direction: 'unidirectional',
    },
    {
      from: 22,
      to: 32,
      relationship: 'Favorites',
      direction: 'unidirectional',
    },
  ],
}
